# Generated by Django 4.1 on 2022-08-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbacks',
            new_name='Feedback',
        ),
    ]
