# Generated by Django 4.1 on 2022-08-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_rename_feedbacks_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Response', 'verbose_name_plural': 'Responses'},
        ),
    ]
