# Generated by Django 4.1 on 2022-08-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_alter_feedback_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Previous Projects',
            },
        ),
    ]
