# Generated by Django 4.1 on 2022-08-22 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='duration',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='endDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='startDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
