# Generated by Django 4.1 on 2022-08-22 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_remove_portfolio_duration_portfolio_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='endDate',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='startDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
